# Generated by Django 4.0.1 on 2022-06-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('a', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
