# Generated by Django 4.0.5 on 2022-06-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='a',
        ),
    ]
